"""
agent/seed_context_db.py — Seed the merchant_context.db SQLite lookup table.

Creates data/merchant_context.db and populates it with synthetic merchant
context records for all merchants generated by the TransactionGenerator.

Usage:
  python -m agent.seed_context_db
  python -m agent.seed_context_db --merchants-file data/merchants.json

The merchant context DB is used by context_fetch.py to enrich spike alerts
with historical risk information.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import sqlite3
from pathlib import Path


_CREATE_SQL = """
CREATE TABLE IF NOT EXISTS merchant_context (
    merchant_id                TEXT PRIMARY KEY,
    risk_tier                  TEXT NOT NULL,
    avg_transaction_value_inr  REAL NOT NULL,
    historical_fp_rate         REAL NOT NULL,
    chargeback_rate            REAL NOT NULL,
    monthly_volume_inr         REAL NOT NULL
);
"""

_INSERT_SQL = """
INSERT OR REPLACE INTO merchant_context
    (merchant_id, risk_tier, avg_transaction_value_inr,
     historical_fp_rate, chargeback_rate, monthly_volume_inr)
VALUES
    (:merchant_id, :risk_tier, :avg_transaction_value_inr,
     :historical_fp_rate, :chargeback_rate, :monthly_volume_inr)
"""

# Seed realistic context per risk tier
_TIER_PROFILES = {
    "low": {
        "avg_transaction_value_inr_range": (50, 2_000),
        "historical_fp_rate_range": (0.05, 0.15),
        "chargeback_rate_range": (0.001, 0.01),
        "monthly_volume_inr_range": (1_00_000, 10_00_000),
    },
    "medium": {
        "avg_transaction_value_inr_range": (500, 10_000),
        "historical_fp_rate_range": (0.10, 0.25),
        "chargeback_rate_range": (0.005, 0.03),
        "monthly_volume_inr_range": (5_00_000, 50_00_000),
    },
    "high": {
        "avg_transaction_value_inr_range": (2_000, 50_000),
        "historical_fp_rate_range": (0.20, 0.40),
        "chargeback_rate_range": (0.02, 0.08),
        "monthly_volume_inr_range": (10_00_000, 5_00_00_000),
    },
}


def seed_from_generator(db_path: str, n_merchants: int = 50, seed: int = 42) -> list[str]:
    """
    Seed the context DB with synthetic merchant records matching the generator's output.
    Returns a list of merchant IDs that were seeded.

    This function is called with the same generator parameters so merchant IDs match.
    """
    from data_gen.generator import TransactionGenerator
    gen = TransactionGenerator(n_merchants=n_merchants, seed=seed)

    rng = random.Random(seed + 9999)
    records = []
    for merchant in gen.merchants:
        tier = merchant.risk_tier
        profile = _TIER_PROFILES[tier]

        records.append({
            "merchant_id": merchant.merchant_id,
            "risk_tier": tier,
            "avg_transaction_value_inr": rng.uniform(*profile["avg_transaction_value_inr_range"]),
            "historical_fp_rate": rng.uniform(*profile["historical_fp_rate_range"]),
            "chargeback_rate": rng.uniform(*profile["chargeback_rate_range"]),
            "monthly_volume_inr": rng.uniform(*profile["monthly_volume_inr_range"]),
        })

    _write_db(db_path, records)
    return [r["merchant_id"] for r in records]


def _write_db(db_path: str, records: list[dict]) -> None:
    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.execute(_CREATE_SQL)
    conn.executemany(_INSERT_SQL, records)
    conn.commit()
    conn.close()
    print(f"Seeded {len(records)} merchant records into {db_path}")


def main():
    parser = argparse.ArgumentParser(description="Seed merchant_context.db")
    parser.add_argument("--db-path", default=os.environ.get("CONTEXT_DB_PATH", "data/merchant_context.db"))
    parser.add_argument("--n-merchants", type=int, default=50)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    merchant_ids = seed_from_generator(
        db_path=args.db_path,
        n_merchants=args.n_merchants,
        seed=args.seed,
    )
    print(f"Done. First 5 merchant IDs: {merchant_ids[:5]}")


if __name__ == "__main__":
    main()
